#!/bin/sh
# Generated by scripts/seed.mjs — uploads seed media into the local R2 bucket.
set -e
cd "$(dirname "$0")/.."
npx wrangler r2 object put "engurhesi-media/images/1fc9fd1f63a9-hero-dam.jpg" --file "static/img/hero-dam.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/bb56da788b23-news-629161708101736.jpg" --file "static/img/news-629161708101736.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/220e4edaff39-news-345601765805312.jpg" --file "static/img/news-345601765805312.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/1a56f709be6a-news-561821759756710.jpg" --file "static/img/news-561821759756710.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/1832cee8a24e-news-507461698150869.jpg" --file "static/img/news-507461698150869.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/dddee416ef4a-operation.jpg" --file "static/img/operation.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/a576cbe86443-activity.jpg" --file "static/img/activity.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/088a4093885c-construction.jpg" --file "static/img/construction.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/52d0e3fdfce8-min-economy.jpg" --file "static/img/partners/min-economy.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/a0a78914f95d-gnerc.png" --file "static/img/partners/gnerc.png" --content-type "image/png" --local
npx wrangler r2 object put "engurhesi-media/images/1ef6e4b980cd-gse.jpg" --file "static/img/partners/gse.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/bd77feb11198-esco.jpg" --file "static/img/partners/esco.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/128d98479f60-energo-pro.jpg" --file "static/img/partners/energo-pro.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/9d88e98dd02c-telasi.jpg" --file "static/img/partners/telasi.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/c58675796789-gedf.jpg" --file "static/img/partners/gedf.jpg" --content-type "image/jpeg" --local
npx wrangler r2 object put "engurhesi-media/images/a2f8ef004f23-genex.jpg" --file "static/img/partners/genex.jpg" --content-type "image/jpeg" --local
